import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // Excel export is a STATIC file (public/exports/monthly_report.xlsx) generated by the
  // openpyxl prep step — no runtime route, no template binary to trace, no serverless fn.
  eslint: {
    // ESLint is run separately; do not block production builds on lint.
    ignoreDuringBuilds: true,
  },
};

export default nextConfig;
